# Generated by Django 3.2.1 on 2021-05-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='id_usr',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='imsi',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='mcc',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='mnc',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='pot_db',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='rssi',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='test_name',
        ),
    ]
