# Generated by Django 3.2.1 on 2021-05-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20210520_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medidas',
        ),
    ]
