# Generated by Django 3.2.1 on 2021-05-20 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_medidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidas',
            name='marca',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
