# Generated by Django 3.2.1 on 2021-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_delete_mccmnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='mccmnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCC', models.CharField(max_length=200)),
                ('MNC', models.CharField(max_length=200)),
                ('OPERADOR', models.CharField(max_length=200)),
                ('ESTADO', models.CharField(max_length=200)),
                ('TECNOLOGIA_FREQ', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bolivia_mccmnc1',
            },
        ),
    ]
