# Generated by Django 3.2.1 on 2021-05-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_mccmnc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mccmnc',
        ),
    ]
