# Generated by Django 3.2.1 on 2021-05-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_delete_mccmnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_bolivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.CharField(max_length=200)),
                ('mnc', models.CharField(max_length=200)),
                ('operador', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('tecnologia_freq', models.CharField(max_length=200)),
            ],
        ),
    ]
