# Generated by Django 3.2.1 on 2021-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_data_bolivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_csvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('id_usr', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=200)),
                ('archivocsv', models.FileField(upload_to='usr_csv/')),
            ],
        ),
    ]
