# Generated by Django 3.2.1 on 2021-05-27 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_user_csvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_csvs',
            name='archivocsv',
            field=models.FileField(upload_to='usr_csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
