# Generated by Django 3.2.1 on 2021-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_user_csvs_archivocsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_csvs',
            name='archivocsv',
            field=models.FileField(upload_to='usr_csv/'),
        ),
    ]
