# Generated by Django 3.2.1 on 2021-06-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_medidas_rssi_dbm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas',
            name='rssi_dbm',
        ),
    ]
