# Generated by Django 3.2.1 on 2021-06-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_torre_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torre_pin',
            old_name='id_usr',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='torre_pin',
            name='imsi',
        ),
        migrations.RemoveField(
            model_name='torre_pin',
            name='mcc',
        ),
        migrations.RemoveField(
            model_name='torre_pin',
            name='mnc',
        ),
        migrations.RemoveField(
            model_name='torre_pin',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='torre_pin',
            name='usuario',
        ),
    ]
