# Generated by Django 3.2.1 on 2021-06-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_auto_20210612_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='torre_pin',
        ),
        migrations.DeleteModel(
            name='torres',
        ),
    ]
