# Generated by Django 3.2.1 on 2021-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0022_alter_torre_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='torre_measure',
            name='distancia',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
