# Generated by Django 3.2.1 on 2021-06-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0023_torre_measure_distancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torre_measure',
            name='id_usr',
        ),
        migrations.RemoveField(
            model_name='torre_measure',
            name='user',
        ),
    ]
