# Generated by Django 3.2.1 on 2021-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0024_auto_20210616_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torre_measure',
            name='torre_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
