# Generated by Django 3.2.1 on 2021-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0026_auto_20210621_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='torre',
            name='mnc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
