# Generated by Django 3.2.8 on 2022-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0028_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
