# Generated by Django 3.2.8 on 2022-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0029_alter_medidas_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='torre_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.CharField(max_length=200)),
                ('mcc', models.CharField(max_length=200)),
                ('net', models.CharField(max_length=200)),
                ('lac', models.CharField(max_length=200)),
                ('cellid', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
                ('cobertura', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
