# Generated by Django 3.2.8 on 2022-04-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0030_torre_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvsT')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='torre_data',
            name='operador',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
