# Generated by Django 3.2.8 on 2022-04-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0031_auto_20220405_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torre_data',
            old_name='radio',
            new_name='tecnologia',
        ),
    ]
